[project]
name = "encrypt-data-assing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cryptography>=45.0.3",
    "fernet>=1.0.1",
    "streamlit>=1.45.1",
]
